"""unique constraint

Revision ID: aaf26c871c4e
Revises: e1f5c71f4002
Create Date: 2020-05-01 01:00:36.196697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf26c871c4e'
down_revision = 'e1f5c71f4002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Venues', ['name', 'city', 'state', 'address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venues', type_='unique')
    # ### end Alembic commands ###
