"""unique constraints artist

Revision ID: bab5b6cfa48b
Revises: aaf26c871c4e
Create Date: 2020-05-01 01:06:03.954105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab5b6cfa48b'
down_revision = 'aaf26c871c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artists', ['name', 'city', 'state', 'genres'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artists', type_='unique')
    # ### end Alembic commands ###
