"""Array for genres

Revision ID: ed8aa3db23f3
Revises: cf60894ee893
Create Date: 2020-04-27 00:06:29.655533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8aa3db23f3'
down_revision = 'cf60894ee893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'genres')
    op.drop_column('Artists', 'genres')
    # ### end Alembic commands ###
